# Generated by Django 4.0 on 2021-12-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Vacation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='desciption',
            new_name='description',
        ),
    ]
